# coding: utf-8

"""
    语雀 OpenAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse20017Data(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'books': 'V2BookStatistics',
        'total': 'object'
    }

    attribute_map = {
        'books': 'books',
        'total': 'total'
    }

    def __init__(self, books=None, total=None):  # noqa: E501
        """InlineResponse20017Data - a model defined in Swagger"""  # noqa: E501
        self._books = None
        self._total = None
        self.discriminator = None
        if books is not None:
            self.books = books
        if total is not None:
            self.total = total

    @property
    def books(self):
        """Gets the books of this InlineResponse20017Data.  # noqa: E501


        :return: The books of this InlineResponse20017Data.  # noqa: E501
        :rtype: V2BookStatistics
        """
        return self._books

    @books.setter
    def books(self, books):
        """Sets the books of this InlineResponse20017Data.


        :param books: The books of this InlineResponse20017Data.  # noqa: E501
        :type: V2BookStatistics
        """

        self._books = books

    @property
    def total(self):
        """Gets the total of this InlineResponse20017Data.  # noqa: E501


        :return: The total of this InlineResponse20017Data.  # noqa: E501
        :rtype: object
        """
        return self._total

    @total.setter
    def total(self, total):
        """Sets the total of this InlineResponse20017Data.


        :param total: The total of this InlineResponse20017Data.  # noqa: E501
        :type: object
        """

        self._total = total

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20017Data, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20017Data):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
