# coding: utf-8

# flake8: noqa
"""
    语雀 OpenAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.inline_response200 import InlineResponse200
from swagger_client.models.inline_response2001 import InlineResponse2001
from swagger_client.models.inline_response20010 import InlineResponse20010
from swagger_client.models.inline_response20011 import InlineResponse20011
from swagger_client.models.inline_response20012 import InlineResponse20012
from swagger_client.models.inline_response20013 import InlineResponse20013
from swagger_client.models.inline_response20014 import InlineResponse20014
from swagger_client.models.inline_response20015 import InlineResponse20015
from swagger_client.models.inline_response20016 import InlineResponse20016
from swagger_client.models.inline_response20016_data import InlineResponse20016Data
from swagger_client.models.inline_response20017 import InlineResponse20017
from swagger_client.models.inline_response20017_data import InlineResponse20017Data
from swagger_client.models.inline_response20018 import InlineResponse20018
from swagger_client.models.inline_response20018_data import InlineResponse20018Data
from swagger_client.models.inline_response2002 import InlineResponse2002
from swagger_client.models.inline_response2002_meta import InlineResponse2002Meta
from swagger_client.models.inline_response2003 import InlineResponse2003
from swagger_client.models.inline_response2004 import InlineResponse2004
from swagger_client.models.inline_response2005 import InlineResponse2005
from swagger_client.models.inline_response2006 import InlineResponse2006
from swagger_client.models.inline_response2006_data import InlineResponse2006Data
from swagger_client.models.inline_response2007 import InlineResponse2007
from swagger_client.models.inline_response2007_meta import InlineResponse2007Meta
from swagger_client.models.inline_response2008 import InlineResponse2008
from swagger_client.models.inline_response2009 import InlineResponse2009
from swagger_client.models.inline_response200_data import InlineResponse200Data
from swagger_client.models.one_of_v2_search_result_target import OneOfV2SearchResultTarget
from swagger_client.models.v2_book import V2Book
from swagger_client.models.v2_book_detail import V2BookDetail
from swagger_client.models.v2_book_statistics import V2BookStatistics
from swagger_client.models.v2_doc import V2Doc
from swagger_client.models.v2_doc_detail import V2DocDetail
from swagger_client.models.v2_doc_statistics import V2DocStatistics
from swagger_client.models.v2_doc_version import V2DocVersion
from swagger_client.models.v2_doc_version_detail import V2DocVersionDetail
from swagger_client.models.v2_group import V2Group
from swagger_client.models.v2_group_statistics import V2GroupStatistics
from swagger_client.models.v2_group_user import V2GroupUser
from swagger_client.models.v2_member_statistics import V2MemberStatistics
from swagger_client.models.v2_search_result import V2SearchResult
from swagger_client.models.v2_tag import V2Tag
from swagger_client.models.v2_toc_item import V2TocItem
from swagger_client.models.v2_user import V2User
