# coding: utf-8

"""
    语雀 OpenAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class GroupApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def group_api_v2_group_member_destroy(self, login, id, **kwargs):  # noqa: E501
        """删除成员  # noqa: E501

        删除成员 DELETE /api/v2/groups/:login/users/:id  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.group_api_v2_group_member_destroy(login, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str login: 团队 Login or ID (required)
        :param str id: 用户 Login or ID (required)
        :return: InlineResponse2006
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.group_api_v2_group_member_destroy_with_http_info(login, id, **kwargs)  # noqa: E501
        else:
            (data) = self.group_api_v2_group_member_destroy_with_http_info(login, id, **kwargs)  # noqa: E501
            return data

    def group_api_v2_group_member_destroy_with_http_info(self, login, id, **kwargs):  # noqa: E501
        """删除成员  # noqa: E501

        删除成员 DELETE /api/v2/groups/:login/users/:id  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.group_api_v2_group_member_destroy_with_http_info(login, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str login: 团队 Login or ID (required)
        :param str id: 用户 Login or ID (required)
        :return: InlineResponse2006
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['login', 'id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method group_api_v2_group_member_destroy" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'login' is set
        if ('login' not in params or
                params['login'] is None):
            raise ValueError("Missing the required parameter `login` when calling `group_api_v2_group_member_destroy`")  # noqa: E501
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `group_api_v2_group_member_destroy`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'login' in params:
            path_params['login'] = params['login']  # noqa: E501
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['authToken']  # noqa: E501

        return self.api_client.call_api(
            '/api/v2/groups/{login}/users/{id}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InlineResponse2006',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def group_api_v2_group_member_list(self, login, **kwargs):  # noqa: E501
        """获取团队的成员  # noqa: E501

        获取团队的成员 GET /api/v2/groups/:login/users   - 支持分页, PageSize 固定为 100    # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.group_api_v2_group_member_list(login, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str login: 团队 Login or ID (required)
        :param str role: 角色 [筛选条件] (0:管理员, 1:成员, 2:只读成员)
        :param int offset: 偏移量 [分页条件]
        :return: InlineResponse2004
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.group_api_v2_group_member_list_with_http_info(login, **kwargs)  # noqa: E501
        else:
            (data) = self.group_api_v2_group_member_list_with_http_info(login, **kwargs)  # noqa: E501
            return data

    def group_api_v2_group_member_list_with_http_info(self, login, **kwargs):  # noqa: E501
        """获取团队的成员  # noqa: E501

        获取团队的成员 GET /api/v2/groups/:login/users   - 支持分页, PageSize 固定为 100    # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.group_api_v2_group_member_list_with_http_info(login, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str login: 团队 Login or ID (required)
        :param str role: 角色 [筛选条件] (0:管理员, 1:成员, 2:只读成员)
        :param int offset: 偏移量 [分页条件]
        :return: InlineResponse2004
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['login', 'role', 'offset']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method group_api_v2_group_member_list" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'login' is set
        if ('login' not in params or
                params['login'] is None):
            raise ValueError("Missing the required parameter `login` when calling `group_api_v2_group_member_list`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'login' in params:
            path_params['login'] = params['login']  # noqa: E501

        query_params = []
        if 'role' in params:
            query_params.append(('role', params['role']))  # noqa: E501
        if 'offset' in params:
            query_params.append(('offset', params['offset']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['authToken']  # noqa: E501

        return self.api_client.call_api(
            '/api/v2/groups/{login}/users', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InlineResponse2004',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def group_api_v2_group_member_update(self, login, id, **kwargs):  # noqa: E501
        """变更成员  # noqa: E501

        变更成员 PUT /api/v2/groups/:login/users/:id    # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.group_api_v2_group_member_update(login, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str login: 团队 Login or ID (required)
        :param str id: 用户 Login or ID (required)
        :param object body:
        :return: InlineResponse2005
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.group_api_v2_group_member_update_with_http_info(login, id, **kwargs)  # noqa: E501
        else:
            (data) = self.group_api_v2_group_member_update_with_http_info(login, id, **kwargs)  # noqa: E501
            return data

    def group_api_v2_group_member_update_with_http_info(self, login, id, **kwargs):  # noqa: E501
        """变更成员  # noqa: E501

        变更成员 PUT /api/v2/groups/:login/users/:id    # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.group_api_v2_group_member_update_with_http_info(login, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str login: 团队 Login or ID (required)
        :param str id: 用户 Login or ID (required)
        :param object body:
        :return: InlineResponse2005
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['login', 'id', 'body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method group_api_v2_group_member_update" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'login' is set
        if ('login' not in params or
                params['login'] is None):
            raise ValueError("Missing the required parameter `login` when calling `group_api_v2_group_member_update`")  # noqa: E501
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `group_api_v2_group_member_update`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'login' in params:
            path_params['login'] = params['login']  # noqa: E501
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['authToken']  # noqa: E501

        return self.api_client.call_api(
            '/api/v2/groups/{login}/users/{id}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InlineResponse2005',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def group_api_v2_user_group_list(self, id, **kwargs):  # noqa: E501
        """获取用户的团队  # noqa: E501

        获取用户的团队 GET /api/v2/users/:id/groups   - 支持分页, PageSize 固定为 100    # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.group_api_v2_user_group_list(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: 用户 login 或 ID (required)
        :param str role: 角色 [过滤条件] (0:管理员, 1:成员)
        :param int offset: 偏移量 [分页条件]
        :return: InlineResponse2003
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.group_api_v2_user_group_list_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.group_api_v2_user_group_list_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def group_api_v2_user_group_list_with_http_info(self, id, **kwargs):  # noqa: E501
        """获取用户的团队  # noqa: E501

        获取用户的团队 GET /api/v2/users/:id/groups   - 支持分页, PageSize 固定为 100    # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.group_api_v2_user_group_list_with_http_info(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: 用户 login 或 ID (required)
        :param str role: 角色 [过滤条件] (0:管理员, 1:成员)
        :param int offset: 偏移量 [分页条件]
        :return: InlineResponse2003
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id', 'role', 'offset']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method group_api_v2_user_group_list" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `group_api_v2_user_group_list`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []
        if 'role' in params:
            query_params.append(('role', params['role']))  # noqa: E501
        if 'offset' in params:
            query_params.append(('offset', params['offset']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['authToken']  # noqa: E501

        return self.api_client.call_api(
            '/api/v2/users/{id}/groups', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InlineResponse2003',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
