# coding: utf-8

"""
    语雀 OpenAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.statistic_api import StatisticApi  # noqa: E501
from swagger_client.rest import ApiException


class TestStatisticApi(unittest.TestCase):
    """StatisticApi unit test stubs"""

    def setUp(self):
        self.api = StatisticApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_statistic_api_v2_statistic_all(self):
        """Test case for statistic_api_v2_statistic_all

        团队.汇总统计数据  # noqa: E501
        """
        pass

    def test_statistic_api_v2_statistic_by_books(self):
        """Test case for statistic_api_v2_statistic_by_books

        团队.知识库统计数据  # noqa: E501
        """
        pass

    def test_statistic_api_v2_statistic_by_docs(self):
        """Test case for statistic_api_v2_statistic_by_docs

        团队.文档统计数据  # noqa: E501
        """
        pass

    def test_statistic_api_v2_statistic_by_members(self):
        """Test case for statistic_api_v2_statistic_by_members

        团队.成员统计数据  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
