# coding: utf-8

"""
    语雀 OpenAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.v2_doc import V2Doc  # noqa: E501
from swagger_client.rest import ApiException


class TestV2Doc(unittest.TestCase):
    """V2Doc unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV2Doc(self):
        """Test V2Doc"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.v2_doc.V2Doc()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
