# coding: utf-8

"""
    语雀 OpenAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.doc_api import DocApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDocApi(unittest.TestCase):
    """DocApi unit test stubs"""

    def setUp(self):
        self.api = DocApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_doc_api_v2_doc_create(self):
        """Test case for doc_api_v2_doc_create

        创建文档  # noqa: E501
        """
        pass

    def test_doc_api_v2_doc_create_by_id(self):
        """Test case for doc_api_v2_doc_create_by_id

        创建文档  # noqa: E501
        """
        pass

    def test_doc_api_v2_doc_destroy(self):
        """Test case for doc_api_v2_doc_destroy

        删除文档  # noqa: E501
        """
        pass

    def test_doc_api_v2_doc_destroy_by_id(self):
        """Test case for doc_api_v2_doc_destroy_by_id

        删除文档  # noqa: E501
        """
        pass

    def test_doc_api_v2_doc_list(self):
        """Test case for doc_api_v2_doc_list

        获取知识库文档列表  # noqa: E501
        """
        pass

    def test_doc_api_v2_doc_list_by_id(self):
        """Test case for doc_api_v2_doc_list_by_id

        获取知识库文档列表  # noqa: E501
        """
        pass

    def test_doc_api_v2_doc_show(self):
        """Test case for doc_api_v2_doc_show

        获取文档详情  # noqa: E501
        """
        pass

    def test_doc_api_v2_doc_show_by_id(self):
        """Test case for doc_api_v2_doc_show_by_id

        获取文档详情  # noqa: E501
        """
        pass

    def test_doc_api_v2_doc_update(self):
        """Test case for doc_api_v2_doc_update

        更新文档  # noqa: E501
        """
        pass

    def test_doc_api_v2_doc_update_by_id(self):
        """Test case for doc_api_v2_doc_update_by_id

        更新文档  # noqa: E501
        """
        pass

    def test_doc_api_v2_doc_version_list(self):
        """Test case for doc_api_v2_doc_version_list

        获取文档历史版本列表  # noqa: E501
        """
        pass

    def test_doc_api_v2_doc_version_show(self):
        """Test case for doc_api_v2_doc_version_show

        获取文档历史版本详情  # noqa: E501
        """
        pass

    def test_doc_api_v2_repo_toc_show(self):
        """Test case for doc_api_v2_repo_toc_show

        获取目录  # noqa: E501
        """
        pass

    def test_doc_api_v2_repo_toc_show_by_id(self):
        """Test case for doc_api_v2_repo_toc_show_by_id

        获取目录  # noqa: E501
        """
        pass

    def test_doc_api_v2_repo_toc_update(self):
        """Test case for doc_api_v2_repo_toc_update

        更新目录  # noqa: E501
        """
        pass

    def test_doc_api_v2_repo_toc_update_by_id(self):
        """Test case for doc_api_v2_repo_toc_update_by_id

        更新目录  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
