# coding: utf-8

"""
    语雀 OpenAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.user_api import UserApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self):
        self.api = UserApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_user_api_v2_hello(self):
        """Test case for user_api_v2_hello

        心跳  # noqa: E501
        """
        pass

    def test_user_api_v2_user_info(self):
        """Test case for user_api_v2_user_info

        获取当前 Token 的用户详情  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
