# coding: utf-8

"""
    语雀 OpenAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.group_api import GroupApi  # noqa: E501
from swagger_client.rest import ApiException


class TestGroupApi(unittest.TestCase):
    """GroupApi unit test stubs"""

    def setUp(self):
        self.api = GroupApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_group_api_v2_group_member_destroy(self):
        """Test case for group_api_v2_group_member_destroy

        删除成员  # noqa: E501
        """
        pass

    def test_group_api_v2_group_member_list(self):
        """Test case for group_api_v2_group_member_list

        获取团队的成员  # noqa: E501
        """
        pass

    def test_group_api_v2_group_member_update(self):
        """Test case for group_api_v2_group_member_update

        变更成员  # noqa: E501
        """
        pass

    def test_group_api_v2_user_group_list(self):
        """Test case for group_api_v2_user_group_list

        获取用户的团队  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
