# coding: utf-8

"""
    语雀 OpenAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.v2_book import V2Book  # noqa: E501
from swagger_client.rest import ApiException


class TestV2Book(unittest.TestCase):
    """V2Book unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV2Book(self):
        """Test V2Book"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.v2_book.V2Book()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
