# coding: utf-8

"""
    语雀 OpenAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.repo_api import RepoApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRepoApi(unittest.TestCase):
    """RepoApi unit test stubs"""

    def setUp(self):
        self.api = RepoApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_repo_api_v2_repo_create(self):
        """Test case for repo_api_v2_repo_create

        创建知识库  # noqa: E501
        """
        pass

    def test_repo_api_v2_repo_create_by_group(self):
        """Test case for repo_api_v2_repo_create_by_group

        创建知识库  # noqa: E501
        """
        pass

    def test_repo_api_v2_repo_destroy(self):
        """Test case for repo_api_v2_repo_destroy

        删除知识库  # noqa: E501
        """
        pass

    def test_repo_api_v2_repo_destroy_by_id(self):
        """Test case for repo_api_v2_repo_destroy_by_id

        删除知识库  # noqa: E501
        """
        pass

    def test_repo_api_v2_repo_list(self):
        """Test case for repo_api_v2_repo_list

        获取知识库列表  # noqa: E501
        """
        pass

    def test_repo_api_v2_repo_list_by_group(self):
        """Test case for repo_api_v2_repo_list_by_group

        获取知识库列表  # noqa: E501
        """
        pass

    def test_repo_api_v2_repo_show(self):
        """Test case for repo_api_v2_repo_show

        获取知识库详情  # noqa: E501
        """
        pass

    def test_repo_api_v2_repo_show_by_id(self):
        """Test case for repo_api_v2_repo_show_by_id

        获取知识库详情  # noqa: E501
        """
        pass

    def test_repo_api_v2_repo_update(self):
        """Test case for repo_api_v2_repo_update

        更新知识库  # noqa: E501
        """
        pass

    def test_repo_api_v2_repo_update_by_id(self):
        """Test case for repo_api_v2_repo_update_by_id

        更新知识库  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
